### ISSUE TITLE
SDR_SIZE mixes bits and bytes

### ISSUE THREAD

**Issue by jorisbontje** [patham9/ANSNA#16]
Is `SDR_SIZE` (defined as 2048) meant to be in bit or bytes?
https://github.com/patham9/ANSNA/blob/master/src/SDR.h#L22

`SDR_Permute` uses it as bits, as it does a bitwise swap from 0 to `SDR_SIZE`. Discussion history on IRC/Riot chat seems to confirm the intention of 2048 bits.

While in the SDR.h block struct definition it is used as bytes,  by defining `SDR_NUM_BLOCKS` (=128 blocks of 16 bytes each), resulting in a 16384 bits structure of which only the first 2048 bits are used by various bit operators.

My suggestion would be to use bits as unit consistently and address this by redefining
https://github.com/patham9/ANSNA/blob/master/src/SDR.h#L25 as:

```c
#define SDR_BLOCK_SIZE (8 * sizeof(SDR_BLOCK_TYPE))
```

**Comment by patham9** [comment]
Thank you! :)
fixed in https://github.com/patham9/ANSNA/commit/64d33db71a625172318d291ab0e2250632ff8306

**Comment by jorisbontje** [comment]
Don't forget the parentheses, otherwise this breaks `#define SDR_NUM_BLOCKS SDR_SIZE / SDR_BLOCK_SIZE`

**Comment by patham9** [comment]
fixed: https://github.com/patham9/ANSNA/commit/8edf149107462ad5718203320270be683b7ea72a
