### ISSUE TITLE
Encode_Scalar off by 2

### ISSUE THREAD

**Issue by jorisbontje** [patham9/ANSNA#17]
The calculation of `int numberOfBuckets = n - w - 1;` in `Encode_Scalar`  is off by 2.
https://github.com/patham9/ANSNA/blob/master/src/Encode.c#L9

According to the paper https://arxiv.org/pdf/1602.05925.pdf it should be `numberOfBuckets = n - w + 1` instead.

<img width="323" alt="screenshot 2018-10-01 16 21 38" src="https://user-images.githubusercontent.com/620959/46294566-5b294e00-c596-11e8-8c36-97e0ca6cad73.png">

With the example values of 72F from the paper
```
n = 120, w = 21, min = 0, max = 100, v = 72
```
we would expect bits 72 to 92 to be set, however the current implementation sets bits 70 to 90. 

For the example value of 100F  
```
n = 120, w = 21, min = 0, max = 100, v = 100
```
we would expect bits 100 to 120 to be set, however the current implementation sets bits 98 to 118.

Correcting the calculation to `numberOfBuckets = n - w + 1` does give the expected result.

**Comment by patham9** [comment]
Awesome contribution, thanks a lot! :)

**Comment by patham9** [comment]
fixed in https://github.com/patham9/ANSNA/commit/64d33db71a625172318d291ab0e2250632ff8306

**Comment by patham9** [comment]
ehm no this one isn't yet, whoops.

**Comment by patham9** [comment]
fixed in https://github.com/patham9/ANSNA/commit/35352504b05dee7ba90e4c7a37c698ab086120fe#diff-20dbb51288a3f33e470cf45abc2eb845R9
