### ISSUE TITLE
derived task type of `Inference_GoalEventDeduction` should be `GOAL` rather than `JUDGEMENT`

### ISSUE THREAD

**Issue by jorisbontje** [patham9/ANSNA#18]
While I am not very conversant in the inference rules, I believe that the derived task type of `Inference_GoalEventDeduction` should be `GOAL` rather than `JUDGEMENT`:

https://github.com/patham9/ANSNA/blob/master/src/Inference.c#L51

**Comment by patham9** [comment]
I fully agree, will fix it in the next commit. Thank you so much for your valuable contributions!

**Comment by patham9** [comment]
fixed in https://github.com/patham9/ANSNA/commit/64d33db71a625172318d291ab0e2250632ff8306
