### ISSUE TITLE
Event cant be EVENT_TYPE_DELETED at this point

### ISSUE THREAD

**Issue by jorisbontje** [patham9/ANSNA#29]
https://github.com/patham9/ANSNA/blob/1d8e19c6f575c604c52909f3db3300d5116caf1b/src/Cycle.c#L4..L10

As we already test `A->event_beliefs.itemsAmount` it doesn't seem that `a->type != EVENT_TYPE_DELETED` is required to test.

**Comment by patham9** [comment]
I agree, will remove it from the condition

**Comment by patham9** [comment]
resolved with: https://github.com/patham9/ANSNA/commit/f8cb7899ce935594f1bcd1e4bec00a14c448c5cf

**Comment by patham9** [comment]
resolved with: https://github.com/patham9/ANSNA/commit/f8cb7899ce935594f1bcd1e4bec00a14c448c5cf
