### ISSUE TITLE
Cycle calling FIFO_AddAndRevise on potentially empty FIFO

### ISSUE THREAD

**Issue by jorisbontje** [patham9/ANSNA#30]
https://github.com/patham9/ANSNA/blob/master/src/Cycle.c#L71

Calling `FIFO_AddAndRevise` on an empty FIFO gives problems down the line, no valid closest `Event` will be found, but it will still try to do `Inference_EventRevision` on it and later trying to call `fifo->array[closest_i] = (Event) {0};` resulting in misery.

**Comment by patham9** [comment]
Thank you! :) Fiixing it already.

**Comment by patham9** [comment]
resolved with: https://github.com/patham9/ANSNA/commit/f8cb7899ce935594f1bcd1e4bec00a14c448c5cf
