### ISSUE TITLE
Memory_getClosestConcept mixes returning a pointer or array index

### ISSUE THREAD

**Issue by jorisbontje** [patham9/ANSNA#34]
https://github.com/patham9/ANSNA/blob/master/src/Memory.c#L97
`Memory_getClosestConcept` returns a pointer when the hashes match and with `USE_HASHING` defined (which it is by default). But further down the function it either returns an the index `i` for `concepts.items[i]` or `MEMORY_MATCH_NO_CONCEPT`.

Probably the intention is to return an index as well in the case of a hash match?

**Comment by patham9** [comment]
I agree, thanks for finding! :) Will be fixed in my next commit I am currently working on.

**Comment by patham9** [comment]
resolved with: https://github.com/patham9/ANSNA/commit/f8cb7899ce935594f1bcd1e4bec00a14c448c5cf
